version: 1.1.{build}
branches:
  only:
  - master
  - stable
skip_tags: true
max_jobs: 1
image:
- Visual Studio 2022
- Visual Studio 2019
clone_depth: 50
install:
  - cmd: >-
      choco install make || VER>NUL
  - cmd: >-
      choco install git || VER>NUL
  - cmd: >-
      choco install python --pre || VER>NUL

      choco upgrade python --pre || VER>NUL
  - cmd: >-
      python -m pip install flake8 || VER>NUL

      python -m pip install coverage || VER>NUL
  - cmd: >-
      choco install codecov || VER>NUL
before_build:
- cmd: >-
    git submodule sync || VER>NUL

    git submodule update --init || VER>NUL

    dir
build_script:
- cmd: make clean
test_script:
- cmd: >-
    make test || VER>NUL

    dir

    coverage combine || VER>NUL

    dir

    coverage xml || VER>NUL

    dir

    codecov || VER>NUL

    dir

    make test-style || VER>NUL
deploy: off
