#! /bin/bash
# Disclaimer of Warranties.
# A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
#    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
#    BY OR ACCESSED THROUGH THIS SHELL SCRIPT IS AT YOUR SOLE RISK AND
#    THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
#    EFFORT IS WITH YOU.
#
# B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
#    AND SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND
#    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT'S LICENSORS
#    (COLLECTIVELY REFERRED TO AS "THE AUTHOR" FOR THE PURPOSES OF THIS DISCLAIMER)
#    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
#    SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
#    NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF
#    MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
#    ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.
#
# C. THE AUTHOR DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE
#    THE AUTHOR's SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN, OR
#    SERVICES PERFORMED OR PROVIDED BY, THIS SHELL SCRIPT WILL MEET YOUR
#    REQUIREMENTS, THAT THE OPERATION OF THIS SHELL SCRIPT OR SERVICES WILL
#    BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICES WILL CONTINUE TO BE MADE
#    AVAILABLE, THAT THIS SHELL SCRIPT OR SERVICES WILL BE COMPATIBLE OR
#    WORK WITH ANY THIRD PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES,
#    OR THAT DEFECTS IN THIS SHELL SCRIPT OR SERVICES WILL BE CORRECTED.
#    INSTALLATION OF THIS THE AUTHOR SOFTWARE MAY AFFECT THE USABILITY OF THIRD
#    PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES.
#
# D. YOU FURTHER ACKNOWLEDGE THAT THIS SHELL SCRIPT AND SERVICES ARE NOT
#    INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE
#    OR TIME DELAYS OF, OR ERRORS OR INACCURACIES IN, THE CONTENT, DATA OR
#    INFORMATION PROVIDED BY THIS SHELL SCRIPT OR SERVICES COULD LEAD TO
#    DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE,
#    INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
#    NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR
#    WEAPONS SYSTEMS.
#
# E. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY THE AUTHOR
#    SHALL CREATE A WARRANTY. SHOULD THIS SHELL SCRIPT OR SERVICES PROVE DEFECTIVE,
#    YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#    Limitation of Liability.
# F. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHOR
#    BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR
#    CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES
#    FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR
#    RECEIVE ANY DATA OR INFORMATION, BUSINESS INTERRUPTION OR ANY OTHER
#    COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR
#    INABILITY TO USE THIS SHELL SCRIPT OR SERVICES OR ANY THIRD PARTY
#    SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH THIS SHELL SCRIPT OR
#    SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
#    TORT OR OTHERWISE) AND EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION
#    OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR
#    CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event
#    shall THE AUTHOR's total liability to you for all damages (other than as may
#    be required by applicable law in cases involving personal injury) exceed
#    the amount of five dollars ($5.00). The foregoing limitations will apply
#    even if the above stated remedy fails of its essential purpose.
################################################################################

# CAVEAT: This Script is for convience and should not be used as a source of truth
# when checking crypto hashes.


# to check though:
diff -q <(tail -n 300 "$0" | head -n 298 | shasum -a 384 -t -) <(tail -n 1 "$0") || exit 70 ;

ulimit -t 90
PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:${PATH}"
LANG=${LANG:-"en_US"}
LC_ALL="${LANG:0:5}.utf-8"
BINDIR="${BINDIR:-./bin}"
DS_TAG="0.8.6"  # circa 2025
umask 127

LOCK_FILE="${TMPDIR:-/tmp}/org.pak.tests.scripts.code-climate.lock"
EXIT_CODE=1
# Function to check if a command exists.
 
# USAGE:
#	~$ check_command CMD
# Arguments:
# CMD (Required) -- Name of the command to check
# Results:
#	exits 64 -- missing required argument
#	exits 126 -- check complete and has failed, can not find given command.
#	returns successful -- check complete and command found to be executable.
function check_command() {
	test -z "$1" && { printf "%s\n" "Error: command name is required to check for existence." >&2 ; exit 64 ; } ;
	local cmd="$1" ;
	# shellcheck disable=SC2086
	test -x "$(command -v ${cmd})" || { printf "%s\n" "Error: Required command '$cmd' is not found." >&2 ; exit 126 ; } ;
}  # end check_command()
# propagate/export function to sub-shells
export -f check_command
 
# Set up CEP-5 shlock helper
hash -p ./.github/tool_shlock_helper.sh shlock || { printf "%s\n" "Error: Failed to register shlock helper. CEP-5 locking will not work." >&2 ; exit 78 ; } ;
check_command cat ;
check_command chmod ;
check_command curl ;
check_command git ;
check_command grep ;
check_command gpg ;
check_command mkdir ;
check_command sed ;  # but will try jq first
check_command shasum ;
check_command shlock ;
check_command tar ;
check_command uname ;

SCRIPT_FILE="tests/fetch-test-reporter"

# Detect the operating system
case "$( command uname -s )" in
	*arwin)
		CI_OS="darwin"
		;;
	Linux)
		CI_OS="linux"
		;;
	*)
		# sorry no windows support here
		printf 'Unsupported OS\n' >&2 ;
		exit 75 ;  # exit code for temporary failure, as per CEP-8
		;;
esac

# Detect the architecture
ARCH="$(command uname -m)"
case "$ARCH" in
	x86_64)
		ARCH="amd64"
		;;
	arm64|aarch64|armv8l)
		ARCH="arm64"
		;;
	armv7l|armv6l)
		ARCH="arm"
		;;
	*)
		# sorry no windows support here
		printf 'Unsupported architecture\n' >&2 ;
		exit 75 ;
		;;
esac

# Set the CI prefix
case "${CI_OS:-Linux}" in
	*arwin)
		CI_ENV_PREFIX="${CI_OS}-amd64"
		;;
	*)
		CI_ENV_PREFIX="${CI_OS}-${ARCH}"
		;;
esac

function cleanup() {
	rm -f "${LOCK_FILE}" 2>/dev/null || : ; wait ;
	rm -f ./test-reporter-latest-${CI_ENV_PREFIX}.sha*.sig 2>/dev/null || : ; wait ;
	rm -f ./test-reporter-latest-${CI_ENV_PREFIX}.sha* 2>/dev/null > /dev/null || : ; wait ;
	rm -f ./ds-cli.sh.sha* 2>/dev/null > /dev/null || : ; wait ;
	unset CI_ENV_PREFIX 2>/dev/null || :
	unset CI_OS 2>/dev/null || :
	unset ARCH 2>/dev/null || :
	unset DS_TAG 2>/dev/null || :
	hash -d shlock 2>/dev/null > /dev/null || : ;
}

if [[ ( $(shlock -f "${LOCK_FILE}" -p $$ ) -eq 0 ) ]] ; then
	EXIT_CODE=0
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
	# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
	#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
	trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null > /dev/null || : ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
	trap 'cleanup ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
else
	# shellcheck disable=SC2046
	printf "\t%s\n" "Fetch Tool already in progress by "$(head "${LOCK_FILE}") >&2 ;
	exit 126 ;
fi

# this is how test files are found:

# THIS IS THE ACTUAL TEST DIR USED (update _TEST_ROOT_DIR as needed)
_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null) ;
if _TEST_ROOT_DIR=$(git rev-parse --show-superproject-working-tree 2>/dev/null); then
	if [ -z "${_TEST_ROOT_DIR}" ]; then
		_TEST_ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null)
	fi
	printf "::debug::%s\n" "Found ${_TEST_ROOT_DIR} ..." ;
else
	printf "::error %s::%s\n" "file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}" \
	"FAIL: missing valid repository or source structure" >&2 ;
	EXIT_CODE=40
fi

# This File  MUST BE GIT-IGNORED
# to be SAFELY USED to store Tokens and env vars (update logic as needed)
if [[ ( -r ./codecov_env ) ]] ; then
	printf "::debug::%s\n" "Found codecov_env ..." ;
	# shellcheck disable=SC2086,SC1091
	source ./codecov_env 2>/dev/null || : ;
fi


#########################
# actual Work starts here
#########################
curl -fLso ./test-reporter-latest-${CI_ENV_PREFIX} "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${CI_ENV_PREFIX}" ;
for i in 1 256 512 ; do
	curl -fLso test-reporter-latest-${CI_ENV_PREFIX}.sha${i} "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${CI_ENV_PREFIX}.sha${i}" ; wait ;
	curl -fLso test-reporter-latest-${CI_ENV_PREFIX}.sha${i}.sig "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${CI_ENV_PREFIX}.sha${i}.sig" ; wait ;
	# test sha1/sha512 signatures if found and sha256 even if not found
	if [[ ( -r test-reporter-latest-${CI_ENV_PREFIX}.sha${i} ) ]] || [[ ( ${i} -eq 256 ) ]] ; then
		if [[ ${i} -eq 1 ]]; then
			printf "%s\n" "WARNING: SHA-1 is deprecated and should be avoided when possible. Consider using SHA-256 or SHA-512 for stronger integrity checks. (CWE-327: Use of a Broken or Risky Cryptographic Algorithm)"
		fi
		if [[ ( -r test-reporter-latest-${CI_ENV_PREFIX}.sha${i}.sig ) ]] ; then
			# configure your CI evironment to trust the key at gpg --keyserver  keys.openpgp.org --recv-keys 9BD9E2DD46DA965A537E5B0A5CBF320243B6FD85
			# FP: KEY FP 9BD9 E2DD 46DA 965A 537E  5B0A 5CBF 3202 43B6 FD85
			# OR...
			# Set CI=true to continue on missing keys
			gpg --verify test-reporter-latest-${CI_ENV_PREFIX}.sha${i}.sig test-reporter-latest-${CI_ENV_PREFIX}.sha${i} || ${CI} 2>/dev/null || ${CIRCLECI} 2>/dev/null || EXIT_CODE=126
			rm -vf test-reporter-latest-${CI_ENV_PREFIX}.sha${i}.sig 2>/dev/null ;
		fi
		shasum -a $i -c --ignore-missing test-reporter-latest-${CI_ENV_PREFIX}.sha${i} || EXIT_CODE=89
		rm -vf test-reporter-latest-${CI_ENV_PREFIX}.sha${i} 2>/dev/null ;
	fi
done

if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
	mv -fv ./test-reporter-latest-${CI_ENV_PREFIX} ./cc-test-reporter 2>/dev/null || EXIT_CODE=126
	chmod -v 751 ./cc-test-reporter || EXIT_CODE=77
fi

if [[ -z ${DEEPSOURCE_DSN} ]] && [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
	printf "::notice %s::%s\n" "file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=SKIP" \
		"No need for Unconfigured DeepSource." ;
elif [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
	printf "%s\n" "Detected Config for DeepSource" ;

	# Make an API call to GitHub to get the latest release with the Accept header
	response=$(curl -s -H "Accept: application/json" "https://api.github.com/repos/DeepSourceCorp/cli/releases/latest")

	# Check if the response is valid
	if [[ "$response" == *"Not Found"* ]]; then
		printf "::warning %s::%s\n" "file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}" \
		"Repository not found or no releases available." >&2 ;
		EXIT_CODE=69
	fi ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		printf "::debug::%s\n" "Checking latest version for DeepSource" ;
		# Try to extract the tag name using jq
		if [[ ( -x "$(command -v jq)" ) ]]; then
			tag_name=$(printf "%s\n" "$response" | jq -r '.tag_name')
		else
			# Fallback to grep and sed if jq is not available
			tag_name=$(printf "%s\n" "$response" | grep -o '"tag_name": "[^"]*' | sed 's/"tag_name": "//')
		fi ;
	fi ;

	# Check if tag_name is empty
	if [[ ( -z "$tag_name" ) ]]; then
		printf "::warning %s::%s\n" "file=${SCRIPT_FILE},line=${BASH_LINENO:-0},title=${FUNCNAME:-$0}" \
		"No tag name found in the response." >&2 ;
		EXIT_CODE=65
	else
		printf "::debug::%s\n" "Found version ${tag_name} for DeepSource" ;
		DS_TAG="${tag_name#v}"
	fi ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		printf "::debug::%s\n" "Creating ${BINDIR} directory for DeepSource" ;
		mkdir -v -m 755 "${BINDIR}" || EXIT_CODE=66 ;
	fi ;

	curl -fLso "deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" "https://github.com/DeepSourceCorp/cli/releases/download/v${DS_TAG}/deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" || EXIT_CODE=125 ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		printf "::debug::%s\n" "Downloaded deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz for DeepSource" ;
	fi ;
	
	curl -fLso "checksums.txt" "https://github.com/DeepSourceCorp/cli/releases/download/v${DS_TAG}/checksums.txt" || EXIT_CODE=125 ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		printf "::debug::%s\n" "Downloaded checksums.txt for DeepSource" ;
		if [[ ( -r checksums.txt ) ]] ; then
			shasum -a 256 -c --ignore-missing checksums.txt || EXIT_CODE=89
			rm -vf checksums.txt 2>/dev/null || : ;
		fi ;
		if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
			printf "%s\n" "Validated deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz for DeepSource" ;
		fi ;
	fi ;
	
	printf "::group::%s\n" "Extracting deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		tar --no-same-owner -xzf "deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" -C "${BINDIR}" || : ;
		rm -vf "deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" 2>/dev/null || : ;
		rm -vfRd "${BINDIR}"/completions/ 2>/dev/null || : ;
		printf "::debug::%s\n" "Extracted deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" ;
	fi ;

	printf "::endgroup::\n" ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		# ref: https://docs.deepsource.com/docs/analyzers-test-coverage#setup-test-coverage
		printf "::debug::%s\n" "Extracted deepsource_${DS_TAG}_${CI_OS}_${ARCH}.tar.gz" ;
		if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
			printf "::debug::%s\n" "Checking for DeepSource CLI" ;
			if [[ ( -d "${BINDIR}" ) ]] ; then
				printf "::debug::=> %s\n" "Found ${BINDIR} directory." ;
				if [[ ( -x "${BINDIR}"/deepsource ) ]] ; then
					printf "::debug::..=> %s\n" "Found ${BINDIR}/deepsource CLI tool" ;
				elif [[ ( -r "${BINDIR}"/deepsource ) || ( -e "${BINDIR}"/deepsource ) ]] ; then
					printf "::debug::..=> %s\n" "Found ${BINDIR}/deepsource file." ;
					printf "::debug::....=> %s\n" "Trying to apply permission corrections" ;
					chmod -v 751 "${BINDIR}"/deepsource || EXIT_CODE=77 ;
					if [[ ( ${EXIT_CODE} -eq 0 ) ]] && [[ ( -x "${BINDIR}"/deepsource ) ]] ; then
						printf "::debug::......=> %s\n" "Fixed ${BINDIR}/deepsource CLI tool" ;
					else
						printf "::debug::....=> %s\n" "Applying corrections Unsuccessful" ;
						EXIT_CODE=77 ;
					fi ;
				else
					printf "::debug::..=> %s\n" "Missing ${BINDIR}/deepsource CLI tool" ;
					EXIT_CODE=66 ;
				fi ;
			else
				printf "::debug::=> %s\n" "Missing ${BINDIR} directory." ;
				EXIT_CODE=66 ;
			fi ;
		fi ;
	fi ;

	if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
		printf "::group::%s\n" "Checking DeepSource Config" ;
		# ref: https://docs.deepsource.com/docs/cli#commands
		./bin/deepsource config validate || ${CI} 2>/dev/null || ${CIRCLECI} 2>/dev/null || EXIT_CODE=125 ;
		printf "::endgroup::\n" ;
	fi ;
	wait ;
fi ;

if [[ ( ${EXIT_CODE} -eq 0 ) ]] ; then
	./cc-test-reporter before-build || EXIT_CODE=125 ;
fi


unset _TEST_ROOT_DIR 2>/dev/null || : ;

cleanup 2>/dev/null || rm -f "${LOCK_FILE}" 2>/dev/null > /dev/null || : ; wait ;

# goodbye
exit ${EXIT_CODE:-255} ;

# This file's code hash:
64775bab23e56bbd695b87b099c23978d789791c79e94ae7c5cd126a99ca7fde949260d9ad26297027db34af2022f436  -
